"""Minimal Home Assistant stand-ins.

The real `homeassistant` PyPI package pulls in native-compiled dependencies
(pyspeex-noise, ciso8601, ...) that are unavailable in a plain dev environment
without a C build toolchain. Since this project only touches a small, stable
slice of the HA API, we provide lightweight real classes/modules for that
slice instead of installing the real package.

Unlike a bare `unittest.mock.MagicMock`, using real `types.ModuleType`
instances with explicitly-wired attributes avoids the classic pitfall where
`from homeassistant import config_entries` (or similar "from package import
submodule" statements) silently returns an autogenerated MagicMock
attribute instead of the submodule we registered in sys.modules.

Loaded automatically by pytest before any test module is collected.
"""
import sys
import types
from datetime import datetime, timezone
from enum import IntFlag
from unittest.mock import MagicMock

import voluptuous as vol


def _new_module(name: str) -> types.ModuleType:
    mod = types.ModuleType(name)
    sys.modules[name] = mod
    return mod


# ---------------------------------------------------------------------------
# homeassistant.core
# ---------------------------------------------------------------------------

def callback(func):
    """No-op stand-in for homeassistant.core.callback."""
    return func


class HomeAssistant:
    """Opaque placeholder — real behaviour is provided by FakeHass in tests."""


ha_core = _new_module("homeassistant.core")
ha_core.callback = callback
ha_core.HomeAssistant = HomeAssistant


# ---------------------------------------------------------------------------
# homeassistant.const
# ---------------------------------------------------------------------------

class Platform:
    COVER = "cover"


ha_const = _new_module("homeassistant.const")
ha_const.CONF_DEVICE_CLASS = "device_class"
ha_const.CONF_NAME = "name"
ha_const.SERVICE_CLOSE_COVER = "close_cover"
ha_const.SERVICE_OPEN_COVER = "open_cover"
ha_const.SERVICE_STOP_COVER = "stop_cover"
ha_const.Platform = Platform


# ---------------------------------------------------------------------------
# homeassistant.helpers.entity — bare-bones Entity base
# ---------------------------------------------------------------------------

class Entity:
    hass = None
    entity_id = None

    def async_write_ha_state(self):
        pass

    def async_schedule_update_ha_state(self, force_refresh: bool = False):
        pass

    def async_on_remove(self, func):
        if not hasattr(self, "_remove_callbacks"):
            self._remove_callbacks = []
        self._remove_callbacks.append(func)


ha_helpers_entity = _new_module("homeassistant.helpers.entity")
ha_helpers_entity.Entity = Entity


# ---------------------------------------------------------------------------
# homeassistant.components.cover
# ---------------------------------------------------------------------------

class CoverEntityFeature(IntFlag):
    OPEN = 1
    CLOSE = 2
    SET_POSITION = 4
    STOP = 8
    OPEN_TILT = 16
    CLOSE_TILT = 32
    STOP_TILT = 64
    SET_TILT_POSITION = 128


class CoverEntity(Entity):
    pass


ha_components = _new_module("homeassistant.components")
ha_cover = _new_module("homeassistant.components.cover")
ha_components.cover = ha_cover
ha_cover.ATTR_CURRENT_POSITION = "current_position"
ha_cover.ATTR_POSITION = "position"
ha_cover.ATTR_TILT_POSITION = "tilt_position"
ha_cover.PLATFORM_SCHEMA = vol.Schema({})
ha_cover.CoverEntity = CoverEntity
ha_cover.CoverEntityFeature = CoverEntityFeature


# ---------------------------------------------------------------------------
# homeassistant.helpers.restore_state
# ---------------------------------------------------------------------------

class RestoreEntity(Entity):
    async def async_get_last_state(self):
        return None


ha_restore_state = _new_module("homeassistant.helpers.restore_state")
ha_restore_state.RestoreEntity = RestoreEntity


# ---------------------------------------------------------------------------
# homeassistant.helpers.template
# ---------------------------------------------------------------------------

class Template:
    def __init__(self, template, hass=None):
        self.template = template
        self.hass = hass

    def async_render(self, parse_result: bool = False):
        return True

    def __eq__(self, other):
        return isinstance(other, Template) and other.template == self.template

    def __repr__(self):
        return f"Template({self.template!r})"


ha_helpers_template = _new_module("homeassistant.helpers.template")
ha_helpers_template.Template = Template


# ---------------------------------------------------------------------------
# homeassistant.helpers.event
# ---------------------------------------------------------------------------

def async_track_time_interval(hass, action, interval):
    return lambda: None


def async_track_state_change_event(hass, entity_ids, action):
    return lambda: None


ha_helpers_event = _new_module("homeassistant.helpers.event")
ha_helpers_event.async_track_time_interval = async_track_time_interval
ha_helpers_event.async_track_state_change_event = async_track_state_change_event


# ---------------------------------------------------------------------------
# homeassistant.util.dt
# ---------------------------------------------------------------------------

def utcnow():
    return datetime.now(timezone.utc)


ha_util = _new_module("homeassistant.util")
ha_util_dt = _new_module("homeassistant.util.dt")
ha_util.dt = ha_util_dt
ha_util_dt.utcnow = utcnow


# ---------------------------------------------------------------------------
# homeassistant.helpers.config_validation
# ---------------------------------------------------------------------------

def _ensure_list(value):
    if value is None:
        return []
    return value if isinstance(value, list) else [value]


ha_cv = _new_module("homeassistant.helpers.config_validation")
ha_cv.string = str
ha_cv.boolean = vol.Boolean()
ha_cv.ensure_list = _ensure_list
ha_cv.positive_int = vol.All(vol.Coerce(int), vol.Range(min=0))
ha_cv.template = lambda value: Template(value)


# ---------------------------------------------------------------------------
# homeassistant.helpers.typing
# ---------------------------------------------------------------------------

ha_typing = _new_module("homeassistant.helpers.typing")
ha_typing.ConfigType = dict


# ---------------------------------------------------------------------------
# homeassistant.helpers.selector (only referenced by config_flow.py)
# ---------------------------------------------------------------------------

ha_selector = _new_module("homeassistant.helpers.selector")


# ---------------------------------------------------------------------------
# homeassistant.helpers.entity_platform
# ---------------------------------------------------------------------------

ha_entity_platform = _new_module("homeassistant.helpers.entity_platform")
ha_entity_platform.async_get_current_platform = MagicMock(return_value=MagicMock())


# ---------------------------------------------------------------------------
# homeassistant.config_entries
# ---------------------------------------------------------------------------

class ConfigEntry:
    pass


class ConfigFlow:
    def __init_subclass__(cls, domain=None, **kwargs):
        super().__init_subclass__(**kwargs)
        cls.domain = domain


class OptionsFlow:
    pass


ha_config_entries = _new_module("homeassistant.config_entries")
ha_config_entries.ConfigEntry = ConfigEntry
ha_config_entries.ConfigFlow = ConfigFlow
ha_config_entries.OptionsFlow = OptionsFlow
ha_config_entries.SOURCE_IMPORT = "import"


# ---------------------------------------------------------------------------
# homeassistant / homeassistant.helpers — top-level namespaces
#
# Wired LAST and explicitly (not via MagicMock) so that "from homeassistant
# import config_entries" and "from homeassistant.helpers import template"
# (and similar single-level "from package import submodule" statements)
# resolve to the exact stub objects registered above, rather than an
# autogenerated MagicMock attribute that would silently shadow them.
# ---------------------------------------------------------------------------

ha_helpers = _new_module("homeassistant.helpers")
ha_helpers.entity = ha_helpers_entity
ha_helpers.restore_state = ha_restore_state
ha_helpers.template = ha_helpers_template
ha_helpers.event = ha_helpers_event
ha_helpers.config_validation = ha_cv
ha_helpers.typing = ha_typing
ha_helpers.selector = ha_selector
ha_helpers.entity_platform = ha_entity_platform

ha = _new_module("homeassistant")
ha.core = ha_core
ha.const = ha_const
ha.components = ha_components
ha.helpers = ha_helpers
ha.util = ha_util
ha.config_entries = ha_config_entries
